language: node_js
node_js:
  - "4"
  - "6"
  - "8"

os: [linux, osx]
dist: trusty
sudo: required

# by caching the npm local cache, instead of ./node_modules,
# we theoretically avoid accidentally having npm keep around
# old modules in the tree
cache:
  directories:
    - $(npm config get cache)

before_install:
  - npm i -g npm@5

install:
  - npm install

script:
  - npm test
