# Node.js
# Build a general Node.js project with yarn.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "vs2017-win2016"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"

  - script: |
      yarn bootstrap
      yarn test
    displayName: "unit_tests_node8"
