name: â„ï¸ Lint

on: [pull_request]

jobs:
  technical-terms:
    name: ğŸŒŒ Check technical terms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ§¹ Scan repo
        run: |
          cd scripts || exit
          sh ./check-technical-terms.sh || exit 1
