on:
  schedule:
    - cron: "0 */12 * * *"
name: Stale Bot workflow
jobs:
  build:
    name: stale
    runs-on: ubuntu-latest
    steps:
      - name: stale
        id: stale
        uses: gatsbyjs/stale@gatsby-repo-test
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAYS_BEFORE_STALE: 20
          DAYS_BEFORE_CLOSE: 10
          DRY_RUN: true
          STALE_ISSUE_MESSAGE: |
            Hiya!

            This issue has gone quiet. Spooky quiet. ðŸ‘»

            We get a lot of issues, so we currently close issues after 30 days of inactivity. Itâ€™s been at least 20 days since the last update here.
            If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not stale" to keep this issue open!
            As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) for more information about opening PRs, triaging issues, and contributing!

            Thanks for being a part of the Gatsby community! ðŸ’ªðŸ’œ
          CLOSE_MESSAGE: |
            Hey again!

            Itâ€™s been 30 days since anything happened on this issue, so our friendly neighborhood robot (thatâ€™s me!) is going to close it.
            Please keep in mind that Iâ€™m only a robot, so if Iâ€™ve closed this issue in error, Iâ€™m `HUMAN_EMOTION_SORRY`. Please feel free to reopen this issue or create a new one if you need anything else.
            As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) for more information about opening PRs, triaging issues, and contributing!

            Thanks again for being part of the Gatsby community! ðŸ’ªðŸ’œ
          EXEMPT_ISSUE_LABELS: |
            not stale
            important
            Epic
            good first issue
            help wanted
            Hacktoberfest
            no triage
            status: confirmed
            type: feature or enhancement
      - name: Post slack report
        uses: pullreminders/slack-action@v1.0.7
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          args: '{\"channel\": \"${{ secrets.SLACK_STALE_CHANNEL_ID }}\", \"text\": \"\", \"blocks\": ${{ steps.stale.outputs.blocks }} }'
