on:
  schedule:
    - cron: 1 0 * * 1,2,3,4,5
name: Reporting workflow
jobs:
  high-priority-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: high-priority-prs
        uses: ./.github/actions/high-priority-prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_CORE_CHANNEL_ID: ${{ secrets.SLACK_CORE_CHANNEL_ID }}
          SLACK_LEARNING_CHANNEL_ID: ${{ secrets.SLACK_LEARNING_CHANNEL_ID }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
